# Generated by Django 2.2.2 on 2019-07-13 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190713_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='chairperson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
