# Generated by Django 2.2.2 on 2019-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190713_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='obj',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
